// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: dag_dag_steps.proto

package scenario_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url    string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Header map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ConnectInfo) Reset() {
	*x = ConnectInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectInfo) ProtoMessage() {}

func (x *ConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectInfo.ProtoReflect.Descriptor instead.
func (*ConnectInfo) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ConnectInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConnectInfo) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

type DAGStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug            string             `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId        string             `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DagId           string             `protobuf:"bytes,4,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	Type            string             `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ConnectInfo     *ConnectInfo       `protobuf:"bytes,6,opt,name=connect_info,json=connectInfo,proto3" json:"connect_info,omitempty"`
	RequestInfo     *structpb.Struct   `protobuf:"bytes,7,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	ConditionAction []*structpb.Struct `protobuf:"bytes,8,rep,name=condition_action,json=conditionAction,proto3" json:"condition_action,omitempty"`
	IsParallel      bool               `protobuf:"varint,9,opt,name=is_parallel,json=isParallel,proto3" json:"is_parallel,omitempty"`
	UiComponent     *structpb.Struct   `protobuf:"bytes,10,opt,name=ui_component,json=uiComponent,proto3" json:"ui_component,omitempty"`
	Title           string             `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	Description     string             `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	CallbackType    string             `protobuf:"bytes,13,opt,name=callback_type,json=callbackType,proto3" json:"callback_type,omitempty"`
	CommitId        string             `protobuf:"bytes,14,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CreatedAt       string             `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *DAGStep) Reset() {
	*x = DAGStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGStep) ProtoMessage() {}

func (x *DAGStep) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGStep.ProtoReflect.Descriptor instead.
func (*DAGStep) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{1}
}

func (x *DAGStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DAGStep) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DAGStep) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *DAGStep) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *DAGStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DAGStep) GetConnectInfo() *ConnectInfo {
	if x != nil {
		return x.ConnectInfo
	}
	return nil
}

func (x *DAGStep) GetRequestInfo() *structpb.Struct {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *DAGStep) GetConditionAction() []*structpb.Struct {
	if x != nil {
		return x.ConditionAction
	}
	return nil
}

func (x *DAGStep) GetIsParallel() bool {
	if x != nil {
		return x.IsParallel
	}
	return false
}

func (x *DAGStep) GetUiComponent() *structpb.Struct {
	if x != nil {
		return x.UiComponent
	}
	return nil
}

func (x *DAGStep) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DAGStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DAGStep) GetCallbackType() string {
	if x != nil {
		return x.CallbackType
	}
	return ""
}

func (x *DAGStep) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *DAGStep) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateDAGStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slug            string             `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	ParentId        string             `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DagId           string             `protobuf:"bytes,3,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	Type            string             `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ConnectInfo     *ConnectInfo       `protobuf:"bytes,5,opt,name=connect_info,json=connectInfo,proto3" json:"connect_info,omitempty"`
	RequestInfo     *structpb.Struct   `protobuf:"bytes,6,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	ConditionAction []*structpb.Struct `protobuf:"bytes,7,rep,name=condition_action,json=conditionAction,proto3" json:"condition_action,omitempty"`
	IsParallel      bool               `protobuf:"varint,8,opt,name=is_parallel,json=isParallel,proto3" json:"is_parallel,omitempty"`
	Title           string             `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	Description     string             `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	CallbackType    string             `protobuf:"bytes,11,opt,name=callback_type,json=callbackType,proto3" json:"callback_type,omitempty"`
	CommitId        string             `protobuf:"bytes,12,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *CreateDAGStepRequest) Reset() {
	*x = CreateDAGStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDAGStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGStepRequest) ProtoMessage() {}

func (x *CreateDAGStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGStepRequest.ProtoReflect.Descriptor instead.
func (*CreateDAGStepRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDAGStepRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateDAGStepRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateDAGStepRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *CreateDAGStepRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateDAGStepRequest) GetConnectInfo() *ConnectInfo {
	if x != nil {
		return x.ConnectInfo
	}
	return nil
}

func (x *CreateDAGStepRequest) GetRequestInfo() *structpb.Struct {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

func (x *CreateDAGStepRequest) GetConditionAction() []*structpb.Struct {
	if x != nil {
		return x.ConditionAction
	}
	return nil
}

func (x *CreateDAGStepRequest) GetIsParallel() bool {
	if x != nil {
		return x.IsParallel
	}
	return false
}

func (x *CreateDAGStepRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDAGStepRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDAGStepRequest) GetCallbackType() string {
	if x != nil {
		return x.CallbackType
	}
	return ""
}

func (x *CreateDAGStepRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetDAGStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DagId string `protobuf:"bytes,3,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
}

func (x *GetDAGStepRequest) Reset() {
	*x = GetDAGStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDAGStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAGStepRequest) ProtoMessage() {}

func (x *GetDAGStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAGStepRequest.ProtoReflect.Descriptor instead.
func (*GetDAGStepRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{3}
}

func (x *GetDAGStepRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDAGStepRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDAGStepRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

type DeleteDAGStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDAGStepRequest) Reset() {
	*x = DeleteDAGStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDAGStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDAGStepRequest) ProtoMessage() {}

func (x *DeleteDAGStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDAGStepRequest.ProtoReflect.Descriptor instead.
func (*DeleteDAGStepRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDAGStepRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DAGStepList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag      *DAG       `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
	DagSteps []*DAGStep `protobuf:"bytes,2,rep,name=dag_steps,json=dagSteps,proto3" json:"dag_steps,omitempty"`
}

func (x *DAGStepList) Reset() {
	*x = DAGStepList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGStepList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGStepList) ProtoMessage() {}

func (x *DAGStepList) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGStepList.ProtoReflect.Descriptor instead.
func (*DAGStepList) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{5}
}

func (x *DAGStepList) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

func (x *DAGStepList) GetDagSteps() []*DAGStep {
	if x != nil {
		return x.DagSteps
	}
	return nil
}

type UpdateDAGStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DagStep *DAGStep `protobuf:"bytes,1,opt,name=dag_step,json=dagStep,proto3" json:"dag_step,omitempty"`
}

func (x *UpdateDAGStepRequest) Reset() {
	*x = UpdateDAGStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDAGStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDAGStepRequest) ProtoMessage() {}

func (x *UpdateDAGStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDAGStepRequest.ProtoReflect.Descriptor instead.
func (*UpdateDAGStepRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDAGStepRequest) GetDagStep() *DAGStep {
	if x != nil {
		return x.DagStep
	}
	return nil
}

type GetAllDAGStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters      *Filters `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	Type         string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DagId        string   `protobuf:"bytes,3,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
	ParentId     string   `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CallbackType string   `protobuf:"bytes,5,opt,name=callback_type,json=callbackType,proto3" json:"callback_type,omitempty"`
	StepId       string   `protobuf:"bytes,6,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	CommitId     string   `protobuf:"bytes,7,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *GetAllDAGStepRequest) Reset() {
	*x = GetAllDAGStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDAGStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDAGStepRequest) ProtoMessage() {}

func (x *GetAllDAGStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDAGStepRequest.ProtoReflect.Descriptor instead.
func (*GetAllDAGStepRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllDAGStepRequest) GetFilters() *Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetAllDAGStepRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetAllDAGStepRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

func (x *GetAllDAGStepRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *GetAllDAGStepRequest) GetCallbackType() string {
	if x != nil {
		return x.CallbackType
	}
	return ""
}

func (x *GetAllDAGStepRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *GetAllDAGStepRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type DAGStepRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DagStepId string `protobuf:"bytes,2,opt,name=dag_step_id,json=dagStepId,proto3" json:"dag_step_id,omitempty"`
}

func (x *DAGStepRunRequest) Reset() {
	*x = DAGStepRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGStepRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGStepRunRequest) ProtoMessage() {}

func (x *DAGStepRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGStepRunRequest.ProtoReflect.Descriptor instead.
func (*DAGStepRunRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{8}
}

func (x *DAGStepRunRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DAGStepRunRequest) GetDagStepId() string {
	if x != nil {
		return x.DagStepId
	}
	return ""
}

type DAGStepRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DAGStepRunResponse) Reset() {
	*x = DAGStepRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGStepRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGStepRunResponse) ProtoMessage() {}

func (x *DAGStepRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGStepRunResponse.ProtoReflect.Descriptor instead.
func (*DAGStepRunResponse) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{9}
}

func (x *DAGStepRunResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type DAG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title      string           `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug       string           `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Type       string           `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Status     string           `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CategoryId string           `protobuf:"bytes,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Attributes *structpb.Struct `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CommitId   string           `protobuf:"bytes,8,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CommitInfo *CommitInfo      `protobuf:"bytes,9,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	CreatedAt  string           `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *DAG) Reset() {
	*x = DAG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAG) ProtoMessage() {}

func (x *DAG) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAG.ProtoReflect.Descriptor instead.
func (*DAG) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{10}
}

func (x *DAG) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DAG) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DAG) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *DAG) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DAG) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DAG) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *DAG) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DAG) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *DAG) GetCommitInfo() *CommitInfo {
	if x != nil {
		return x.CommitInfo
	}
	return nil
}

func (x *DAG) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag *DAG `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
}

func (x *CreateDAGRequest) Reset() {
	*x = CreateDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDAGRequest) ProtoMessage() {}

func (x *CreateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDAGRequest.ProtoReflect.Descriptor instead.
func (*CreateDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDAGRequest) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

type GetDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionId string `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	CommitId  string `protobuf:"bytes,3,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *GetDAGRequest) Reset() {
	*x = GetDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDAGRequest) ProtoMessage() {}

func (x *GetDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDAGRequest.ProtoReflect.Descriptor instead.
func (*GetDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{12}
}

func (x *GetDAGRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDAGRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetDAGRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetAllDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter     *Filters `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	CategoryId string   `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	VersionId  string   `protobuf:"bytes,3,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	CommitId   string   `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *GetAllDAGRequest) Reset() {
	*x = GetAllDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDAGRequest) ProtoMessage() {}

func (x *GetAllDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDAGRequest.ProtoReflect.Descriptor instead.
func (*GetAllDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllDAGRequest) GetFilter() *Filters {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetAllDAGRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetAllDAGRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *GetAllDAGRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type DAGList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DAGs  []*DAG `protobuf:"bytes,1,rep,name=DAGs,proto3" json:"DAGs,omitempty"`
	Count int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *DAGList) Reset() {
	*x = DAGList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAGList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAGList) ProtoMessage() {}

func (x *DAGList) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAGList.ProtoReflect.Descriptor instead.
func (*DAGList) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{14}
}

func (x *DAGList) GetDAGs() []*DAG {
	if x != nil {
		return x.DAGs
	}
	return nil
}

func (x *DAGList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDAGRequest) Reset() {
	*x = DeleteDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDAGRequest) ProtoMessage() {}

func (x *DeleteDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDAGRequest.ProtoReflect.Descriptor instead.
func (*DeleteDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteDAGRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDAGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag *DAG `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
}

func (x *UpdateDAGRequest) Reset() {
	*x = UpdateDAGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDAGRequest) ProtoMessage() {}

func (x *UpdateDAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDAGRequest.ProtoReflect.Descriptor instead.
func (*UpdateDAGRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDAGRequest) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

type CreateScenarioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dag           *DAG        `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
	Steps         []*DAGStep  `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	CommitInfo    *CommitInfo `protobuf:"bytes,3,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	ProjectId     string      `protobuf:"bytes,4,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string      `protobuf:"bytes,5,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	CommitId      string      `protobuf:"bytes,6,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *CreateScenarioRequest) Reset() {
	*x = CreateScenarioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioRequest) ProtoMessage() {}

func (x *CreateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioRequest.ProtoReflect.Descriptor instead.
func (*CreateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{17}
}

func (x *CreateScenarioRequest) GetDag() *DAG {
	if x != nil {
		return x.Dag
	}
	return nil
}

func (x *CreateScenarioRequest) GetSteps() []*DAGStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CreateScenarioRequest) GetCommitInfo() *CommitInfo {
	if x != nil {
		return x.CommitInfo
	}
	return nil
}

func (x *CreateScenarioRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateScenarioRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CreateScenarioRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetScenarioHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId     string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	DagId         string `protobuf:"bytes,3,opt,name=dag_id,json=dagId,proto3" json:"dag_id,omitempty"`
}

func (x *GetScenarioHistoryRequest) Reset() {
	*x = GetScenarioHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScenarioHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioHistoryRequest) ProtoMessage() {}

func (x *GetScenarioHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioHistoryRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{18}
}

func (x *GetScenarioHistoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetScenarioHistoryRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetScenarioHistoryRequest) GetDagId() string {
	if x != nil {
		return x.DagId
	}
	return ""
}

type Commit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitInfo   *CommitInfo `protobuf:"bytes,1,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	VersionInfos []string    `protobuf:"bytes,2,rep,name=version_infos,json=versionInfos,proto3" json:"version_infos,omitempty"`
	CreatedAt    string      `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    string      `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Commit) Reset() {
	*x = Commit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{19}
}

func (x *Commit) GetCommitInfo() *CommitInfo {
	if x != nil {
		return x.CommitInfo
	}
	return nil
}

func (x *Commit) GetVersionInfos() []string {
	if x != nil {
		return x.VersionInfos
	}
	return nil
}

func (x *Commit) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Commit) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetScenarioHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commits []*Commit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	Count   int64     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Id      string    `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetScenarioHistoryResponse) Reset() {
	*x = GetScenarioHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScenarioHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioHistoryResponse) ProtoMessage() {}

func (x *GetScenarioHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioHistoryResponse) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{20}
}

func (x *GetScenarioHistoryResponse) GetCommits() []*Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

func (x *GetScenarioHistoryResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetScenarioHistoryResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevertScenarioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewCommitId   string      `protobuf:"bytes,1,opt,name=new_commit_id,json=newCommitId,proto3" json:"new_commit_id,omitempty"`
	VersionId     string      `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	Id            string      `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	OldCommitId   string      `protobuf:"bytes,4,opt,name=old_commit_id,json=oldCommitId,proto3" json:"old_commit_id,omitempty"`
	ProjectId     string      `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	EnvironmentId string      `protobuf:"bytes,6,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	CommitInfo    *CommitInfo `protobuf:"bytes,7,opt,name=commit_info,json=commitInfo,proto3" json:"commit_info,omitempty"`
	VersionIds    []string    `protobuf:"bytes,8,rep,name=version_ids,json=versionIds,proto3" json:"version_ids,omitempty"`
}

func (x *RevertScenarioRequest) Reset() {
	*x = RevertScenarioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevertScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertScenarioRequest) ProtoMessage() {}

func (x *RevertScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertScenarioRequest.ProtoReflect.Descriptor instead.
func (*RevertScenarioRequest) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{21}
}

func (x *RevertScenarioRequest) GetNewCommitId() string {
	if x != nil {
		return x.NewCommitId
	}
	return ""
}

func (x *RevertScenarioRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *RevertScenarioRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevertScenarioRequest) GetOldCommitId() string {
	if x != nil {
		return x.OldCommitId
	}
	return ""
}

func (x *RevertScenarioRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RevertScenarioRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *RevertScenarioRequest) GetCommitInfo() *CommitInfo {
	if x != nil {
		return x.CommitInfo
	}
	return nil
}

func (x *RevertScenarioRequest) GetVersionIds() []string {
	if x != nil {
		return x.VersionIds
	}
	return nil
}

type RevertScenarioResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommitId string `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
}

func (x *RevertScenarioResponse) Reset() {
	*x = RevertScenarioResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_dag_steps_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevertScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevertScenarioResponse) ProtoMessage() {}

func (x *RevertScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dag_dag_steps_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevertScenarioResponse.ProtoReflect.Descriptor instead.
func (*RevertScenarioResponse) Descriptor() ([]byte, []int) {
	return file_dag_dag_steps_proto_rawDescGZIP(), []int{22}
}

func (x *RevertScenarioResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevertScenarioResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

var File_dag_dag_steps_proto protoreflect.FileDescriptor

var file_dag_dag_steps_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x61, 0x67, 0x5f, 0x64, 0x61, 0x67, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x72, 0x75, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x41, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x39, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xad, 0x04, 0x0a, 0x07, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x15, 0x0a, 0x06, 0x64, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x64, 0x61, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0c,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x73, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x12, 0x3a, 0x0a,
	0x0c, 0x75, 0x69, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x75, 0x69,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0xcf, 0x03, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x41, 0x47,
	0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x64, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61,
	0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f,
	0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x41, 0x47, 0x53, 0x74,
	0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x64, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x61, 0x67, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x41,
	0x47, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6e, 0x0a, 0x0b,
	0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52,
	0x03, 0x64, 0x61, 0x67, 0x12, 0x36, 0x0a, 0x09, 0x64, 0x61, 0x67, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x53, 0x74,
	0x65, 0x70, 0x52, 0x08, 0x64, 0x61, 0x67, 0x53, 0x74, 0x65, 0x70, 0x73, 0x22, 0x4c, 0x0a, 0x14,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x64, 0x61, 0x67, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65,
	0x70, 0x52, 0x07, 0x64, 0x61, 0x67, 0x53, 0x74, 0x65, 0x70, 0x22, 0xee, 0x01, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x64, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61,
	0x67, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x11, 0x44,
	0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x64, 0x61, 0x67, 0x5f, 0x73, 0x74, 0x65, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x61, 0x67, 0x53, 0x74,
	0x65, 0x70, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0xc0, 0x02, 0x0a, 0x03, 0x44, 0x41, 0x47, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x73, 0x6c, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x12, 0x37, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x3b, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x41, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x61, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52, 0x03, 0x64,
	0x61, 0x67, 0x22, 0x5b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x22,
	0xa2, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52,
	0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x07, 0x44, 0x41, 0x47, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x29, 0x0a, 0x04, 0x44, 0x41, 0x47, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x44, 0x41, 0x47, 0x52, 0x04, 0x44, 0x41, 0x47, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x41, 0x47, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x41,
	0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52, 0x03, 0x64, 0x61,
	0x67, 0x22, 0x93, 0x02, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x64,
	0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x52,
	0x03, 0x64, 0x61, 0x67, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x41, 0x47, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05,
	0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x3d, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x61,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x67, 0x49,
	0x64, 0x22, 0xaa, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x3d, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x76,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xb4, 0x02, 0x0a, 0x15, 0x52, 0x65, 0x76, 0x65, 0x72,
	0x74, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x6c, 0x64, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6c, 0x64, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3d, 0x0a,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x45, 0x0a,
	0x16, 0x52, 0x65, 0x76, 0x65, 0x72, 0x74, 0x53, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x49, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dag_dag_steps_proto_rawDescOnce sync.Once
	file_dag_dag_steps_proto_rawDescData = file_dag_dag_steps_proto_rawDesc
)

func file_dag_dag_steps_proto_rawDescGZIP() []byte {
	file_dag_dag_steps_proto_rawDescOnce.Do(func() {
		file_dag_dag_steps_proto_rawDescData = protoimpl.X.CompressGZIP(file_dag_dag_steps_proto_rawDescData)
	})
	return file_dag_dag_steps_proto_rawDescData
}

var file_dag_dag_steps_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_dag_dag_steps_proto_goTypes = []interface{}{
	(*ConnectInfo)(nil),                // 0: scenario_service.ConnectInfo
	(*DAGStep)(nil),                    // 1: scenario_service.DAGStep
	(*CreateDAGStepRequest)(nil),       // 2: scenario_service.CreateDAGStepRequest
	(*GetDAGStepRequest)(nil),          // 3: scenario_service.GetDAGStepRequest
	(*DeleteDAGStepRequest)(nil),       // 4: scenario_service.DeleteDAGStepRequest
	(*DAGStepList)(nil),                // 5: scenario_service.DAGStepList
	(*UpdateDAGStepRequest)(nil),       // 6: scenario_service.UpdateDAGStepRequest
	(*GetAllDAGStepRequest)(nil),       // 7: scenario_service.GetAllDAGStepRequest
	(*DAGStepRunRequest)(nil),          // 8: scenario_service.DAGStepRunRequest
	(*DAGStepRunResponse)(nil),         // 9: scenario_service.DAGStepRunResponse
	(*DAG)(nil),                        // 10: scenario_service.DAG
	(*CreateDAGRequest)(nil),           // 11: scenario_service.CreateDAGRequest
	(*GetDAGRequest)(nil),              // 12: scenario_service.GetDAGRequest
	(*GetAllDAGRequest)(nil),           // 13: scenario_service.GetAllDAGRequest
	(*DAGList)(nil),                    // 14: scenario_service.DAGList
	(*DeleteDAGRequest)(nil),           // 15: scenario_service.DeleteDAGRequest
	(*UpdateDAGRequest)(nil),           // 16: scenario_service.UpdateDAGRequest
	(*CreateScenarioRequest)(nil),      // 17: scenario_service.CreateScenarioRequest
	(*GetScenarioHistoryRequest)(nil),  // 18: scenario_service.GetScenarioHistoryRequest
	(*Commit)(nil),                     // 19: scenario_service.Commit
	(*GetScenarioHistoryResponse)(nil), // 20: scenario_service.GetScenarioHistoryResponse
	(*RevertScenarioRequest)(nil),      // 21: scenario_service.RevertScenarioRequest
	(*RevertScenarioResponse)(nil),     // 22: scenario_service.RevertScenarioResponse
	nil,                                // 23: scenario_service.ConnectInfo.HeaderEntry
	(*structpb.Struct)(nil),            // 24: google.protobuf.Struct
	(*Filters)(nil),                    // 25: scenario_service.Filters
	(*CommitInfo)(nil),                 // 26: scenario_service.CommitInfo
}
var file_dag_dag_steps_proto_depIdxs = []int32{
	23, // 0: scenario_service.ConnectInfo.header:type_name -> scenario_service.ConnectInfo.HeaderEntry
	0,  // 1: scenario_service.DAGStep.connect_info:type_name -> scenario_service.ConnectInfo
	24, // 2: scenario_service.DAGStep.request_info:type_name -> google.protobuf.Struct
	24, // 3: scenario_service.DAGStep.condition_action:type_name -> google.protobuf.Struct
	24, // 4: scenario_service.DAGStep.ui_component:type_name -> google.protobuf.Struct
	0,  // 5: scenario_service.CreateDAGStepRequest.connect_info:type_name -> scenario_service.ConnectInfo
	24, // 6: scenario_service.CreateDAGStepRequest.request_info:type_name -> google.protobuf.Struct
	24, // 7: scenario_service.CreateDAGStepRequest.condition_action:type_name -> google.protobuf.Struct
	10, // 8: scenario_service.DAGStepList.dag:type_name -> scenario_service.DAG
	1,  // 9: scenario_service.DAGStepList.dag_steps:type_name -> scenario_service.DAGStep
	1,  // 10: scenario_service.UpdateDAGStepRequest.dag_step:type_name -> scenario_service.DAGStep
	25, // 11: scenario_service.GetAllDAGStepRequest.filters:type_name -> scenario_service.Filters
	24, // 12: scenario_service.DAG.attributes:type_name -> google.protobuf.Struct
	26, // 13: scenario_service.DAG.commit_info:type_name -> scenario_service.CommitInfo
	10, // 14: scenario_service.CreateDAGRequest.dag:type_name -> scenario_service.DAG
	25, // 15: scenario_service.GetAllDAGRequest.filter:type_name -> scenario_service.Filters
	10, // 16: scenario_service.DAGList.DAGs:type_name -> scenario_service.DAG
	10, // 17: scenario_service.UpdateDAGRequest.dag:type_name -> scenario_service.DAG
	10, // 18: scenario_service.CreateScenarioRequest.dag:type_name -> scenario_service.DAG
	1,  // 19: scenario_service.CreateScenarioRequest.steps:type_name -> scenario_service.DAGStep
	26, // 20: scenario_service.CreateScenarioRequest.commit_info:type_name -> scenario_service.CommitInfo
	26, // 21: scenario_service.Commit.commit_info:type_name -> scenario_service.CommitInfo
	19, // 22: scenario_service.GetScenarioHistoryResponse.commits:type_name -> scenario_service.Commit
	26, // 23: scenario_service.RevertScenarioRequest.commit_info:type_name -> scenario_service.CommitInfo
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_dag_dag_steps_proto_init() }
func file_dag_dag_steps_proto_init() {
	if File_dag_dag_steps_proto != nil {
		return
	}
	file_common_proto_init()
	file_run_service_proto_init()
	file_category_proto_init()
	file_scenario_commit_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dag_dag_steps_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDAGStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDAGStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDAGStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGStepList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDAGStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDAGStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGStepRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGStepRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DAGList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDAGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScenarioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScenarioHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Commit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScenarioHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevertScenarioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_dag_steps_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevertScenarioResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dag_dag_steps_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dag_dag_steps_proto_goTypes,
		DependencyIndexes: file_dag_dag_steps_proto_depIdxs,
		MessageInfos:      file_dag_dag_steps_proto_msgTypes,
	}.Build()
	File_dag_dag_steps_proto = out.File
	file_dag_dag_steps_proto_rawDesc = nil
	file_dag_dag_steps_proto_goTypes = nil
	file_dag_dag_steps_proto_depIdxs = nil
}
