// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: new_function_project.proto

package new_function_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FunctionProjectServiceClient is the client API for FunctionProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FunctionProjectServiceClient interface {
	Register(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterProjects(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Deregister(ctx context.Context, in *DeregisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Reconnect(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RegisterMany(ctx context.Context, in *RegisterManyProjectsRequest, opts ...grpc.CallOption) (*RegisterManyProjectsResponse, error)
	DeregisterMany(ctx context.Context, in *DeregisterManyProjectsRequest, opts ...grpc.CallOption) (*DeregisterManyProjectsResponse, error)
}

type functionProjectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFunctionProjectServiceClient(cc grpc.ClientConnInterface) FunctionProjectServiceClient {
	return &functionProjectServiceClient{cc}
}

func (c *functionProjectServiceClient) Register(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionProjectServiceClient) RegisterProjects(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/RegisterProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionProjectServiceClient) Deregister(ctx context.Context, in *DeregisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/Deregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionProjectServiceClient) Reconnect(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/Reconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionProjectServiceClient) RegisterMany(ctx context.Context, in *RegisterManyProjectsRequest, opts ...grpc.CallOption) (*RegisterManyProjectsResponse, error) {
	out := new(RegisterManyProjectsResponse)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/RegisterMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *functionProjectServiceClient) DeregisterMany(ctx context.Context, in *DeregisterManyProjectsRequest, opts ...grpc.CallOption) (*DeregisterManyProjectsResponse, error) {
	out := new(DeregisterManyProjectsResponse)
	err := c.cc.Invoke(ctx, "/new_function_service.FunctionProjectService/DeregisterMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FunctionProjectServiceServer is the server API for FunctionProjectService service.
// All implementations must embed UnimplementedFunctionProjectServiceServer
// for forward compatibility
type FunctionProjectServiceServer interface {
	Register(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error)
	RegisterProjects(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error)
	Deregister(context.Context, *DeregisterProjectRequest) (*emptypb.Empty, error)
	Reconnect(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error)
	RegisterMany(context.Context, *RegisterManyProjectsRequest) (*RegisterManyProjectsResponse, error)
	DeregisterMany(context.Context, *DeregisterManyProjectsRequest) (*DeregisterManyProjectsResponse, error)
	mustEmbedUnimplementedFunctionProjectServiceServer()
}

// UnimplementedFunctionProjectServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFunctionProjectServiceServer struct {
}

func (UnimplementedFunctionProjectServiceServer) Register(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFunctionProjectServiceServer) RegisterProjects(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProjects not implemented")
}
func (UnimplementedFunctionProjectServiceServer) Deregister(context.Context, *DeregisterProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedFunctionProjectServiceServer) Reconnect(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reconnect not implemented")
}
func (UnimplementedFunctionProjectServiceServer) RegisterMany(context.Context, *RegisterManyProjectsRequest) (*RegisterManyProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterMany not implemented")
}
func (UnimplementedFunctionProjectServiceServer) DeregisterMany(context.Context, *DeregisterManyProjectsRequest) (*DeregisterManyProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterMany not implemented")
}
func (UnimplementedFunctionProjectServiceServer) mustEmbedUnimplementedFunctionProjectServiceServer() {
}

// UnsafeFunctionProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FunctionProjectServiceServer will
// result in compilation errors.
type UnsafeFunctionProjectServiceServer interface {
	mustEmbedUnimplementedFunctionProjectServiceServer()
}

func RegisterFunctionProjectServiceServer(s grpc.ServiceRegistrar, srv FunctionProjectServiceServer) {
	s.RegisterService(&FunctionProjectService_ServiceDesc, srv)
}

func _FunctionProjectService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).Register(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionProjectService_RegisterProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).RegisterProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/RegisterProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).RegisterProjects(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionProjectService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).Deregister(ctx, req.(*DeregisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionProjectService_Reconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).Reconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/Reconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).Reconnect(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionProjectService_RegisterMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterManyProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).RegisterMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/RegisterMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).RegisterMany(ctx, req.(*RegisterManyProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FunctionProjectService_DeregisterMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterManyProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FunctionProjectServiceServer).DeregisterMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/new_function_service.FunctionProjectService/DeregisterMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FunctionProjectServiceServer).DeregisterMany(ctx, req.(*DeregisterManyProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FunctionProjectService_ServiceDesc is the grpc.ServiceDesc for FunctionProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FunctionProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "new_function_service.FunctionProjectService",
	HandlerType: (*FunctionProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _FunctionProjectService_Register_Handler,
		},
		{
			MethodName: "RegisterProjects",
			Handler:    _FunctionProjectService_RegisterProjects_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _FunctionProjectService_Deregister_Handler,
		},
		{
			MethodName: "Reconnect",
			Handler:    _FunctionProjectService_Reconnect_Handler,
		},
		{
			MethodName: "RegisterMany",
			Handler:    _FunctionProjectService_RegisterMany_Handler,
		},
		{
			MethodName: "DeregisterMany",
			Handler:    _FunctionProjectService_DeregisterMany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "new_function_project.proto",
}
